### ISSUE TITLE
When can a APK be expected?

### ISSUE THREAD

**Issue by nonetrix** [abb128/WhisperVoiceInput#1]
I would like to try this even if it is extremely buggy, however I don't really feel like going through the hassle of building it myself. Perhaps APKs could be released? Also, I am pretty sure Github actions can automate this every time you make a push to Github, I know Lawnchair does this. Thanks for making this possible!

**Comment by abb128** [comment]
The APK is currently very unoptimized (475MB), so it will probably need to be optimized first

**Comment by sol8712** [comment]
I would absolutely love an apk, if possible, for this.
I cant speak for everyone but..... i dont care if it uses 2000MB and 100% cpu while i use it. Ill appreciate every second.
You will have many people submitting bug reports(including me) and hopefully PR's.

Setting up Github actions will only allow those with Github accounts to see and download the built .apk, further alerting people to the very very early stage of the app and it will not show up on the releases page, if thats a concern.

Huge thanks you for all your great and important work! And a thanks to Mr Rossmann for his assistance and bringing me here.

**Comment by abb128** [comment]
Sorry for the delay. I've been developing Voice Input as a FUTO project and I'm happy to announce that an APK and Play Store listing are available at https://voiceinput.futo.org

If you have any questions or issues, feel free to let me know here or to send an email

**Comment by nonetrix** [comment]
Thanks so much this is already blowing my mind, it's much better than Google even with understanding my voice/accent! And japanese support is really great since I'm learning Japanese, but it's hit or miss with Japanese but I imagine 90% of that is me sucking at speaking it. Definitely will be using this a lot

**Comment by nonetrix** [comment]
Another idea might be to make a Linux version, I don't even think Windows has voice typing? However I could be wrong. Might be willing to donate a little for that since I think it would be neat and probably fairly easy to I imagine, I think typing booster might be a good place to look for how to do something like this
https://mike-fabian.github.io/ibus-typing-booster/
